//Maya Preference 2016.5 (Release 1)
//
//
evalDeferred("autoLoadPlugin(\"\", \"objExport\", \"objExport\")");
evalDeferred("autoLoadPlugin(\"\", \"Mayatomr\", \"Mayatomr\")");
evalDeferred("autoLoadPlugin(\"\", \"autoLoader\", \"autoLoader\")");
evalDeferred("autoLoadPlugin(\"\", \"ik2Bsolver\", \"ik2Bsolver\")");
evalDeferred("autoLoadPlugin(\"\", \"fbxmaya\", \"fbxmaya\")");
//evalDeferred("autoLoadPlugin(\"\", \"modelingToolkit\", \"modelingToolkit\")");
